"""Add reviewed column to thread_labels

Revision ID: 205e2f2e0c75
Revises: change_message_id_to_string
Create Date: 2025-04-14 08:47:02.524414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205e2f2e0c75'
down_revision: Union[str, None] = 'change_message_id_to_string'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_labels', sa.Column('reviewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread_labels', 'reviewed')
    # ### end Alembic commands ###
