"""initial

Revision ID: 479658f6f92d
Revises: 
Create Date: 2025-06-21 13:20:20.432026

"""
from typing import Sequence, Union

import pgvector
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479658f6f92d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('space_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('person_email', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.room_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('processed_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('processed_text', sa.Text(), nullable=False),
    sa.Column('solution_detected', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_labels',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('solution_message_id', sa.String(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.ForeignKeyConstraint(['solution_message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_labels')
    op.drop_table('processed_messages')
    op.drop_table('embeddings')
    op.drop_table('classifications')
    op.drop_table('messages')
    op.drop_table('spaces')
    # ### end Alembic commands ###
