"""initial migration

Revision ID: 7fcdddb5ba0f
Revises: 
Create Date: 2025-03-25 18:48:41.337869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fcdddb5ba0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('embeddings_vector_idx', table_name='embeddings', postgresql_using='ivfflat')
    op.drop_constraint('embeddings_message_id_fkey', 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'messages', ['message_id'], ['id'])
    op.drop_index('messages_text_idx', table_name='messages', postgresql_using='gin')
    op.drop_constraint('messages_space_id_fkey', 'messages', type_='foreignkey')
    op.alter_column('processed_messages', 'solution_detected',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('thread_labels', 'topic_label',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('thread_labels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'thread_labels', 'messages', ['solution_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread_labels', type_='foreignkey')
    op.alter_column('thread_labels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('thread_labels', 'topic_label',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('processed_messages', 'solution_detected',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('messages_space_id_fkey', 'messages', 'spaces', ['space_id'], ['room_id'], ondelete='CASCADE')
    op.create_index('messages_text_idx', 'messages', [sa.literal_column("to_tsvector('english'::regconfig, text)")], unique=False, postgresql_using='gin')
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key('embeddings_message_id_fkey', 'embeddings', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_index('embeddings_vector_idx', 'embeddings', ['vector'], unique=False, postgresql_using='ivfflat')
    # ### end Alembic commands ###
