"""Fix foreign key ambiguity in ThreadLabels

Revision ID: 83dca7551ed4
Revises: 1eabb64ecf54
Create Date: 2025-04-12 12:15:05.980832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83dca7551ed4'
down_revision: Union[str, None] = '1eabb64ecf54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
