"""Add thread_labels table with solution column

Revision ID: 9019bb6cec00
Revises: ac76e8474eef
Create Date: 2025-04-12 09:50:38.815989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9019bb6cec00'
down_revision: Union[str, None] = 'ac76e8474eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_labels', sa.Column('message_id', sa.UUID(), nullable=False))
    op.add_column('thread_labels', sa.Column('label', sa.String(length=20), nullable=False))
    op.add_column('thread_labels', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.drop_constraint('thread_labels_solution_message_id_fkey', 'thread_labels', type_='foreignkey')
    op.create_foreign_key(None, 'thread_labels', 'messages', ['solution_message_id'], ['id'])
    op.create_foreign_key(None, 'thread_labels', 'messages', ['message_id'], ['id'])
    op.drop_column('thread_labels', 'created_at')
    op.drop_column('thread_labels', 'thread_id')
    op.drop_column('thread_labels', 'topic_label')
    op.drop_column('thread_labels', 'solution_confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_labels', sa.Column('solution_confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('thread_labels', sa.Column('topic_label', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('thread_labels', sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('thread_labels', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'thread_labels', type_='foreignkey')
    op.drop_constraint(None, 'thread_labels', type_='foreignkey')
    op.create_foreign_key('thread_labels_solution_message_id_fkey', 'thread_labels', 'messages', ['solution_message_id'], ['id'], ondelete='SET NULL')
    op.drop_column('thread_labels', 'confidence_score')
    op.drop_column('thread_labels', 'label')
    op.drop_column('thread_labels', 'message_id')
    # ### end Alembic commands ###
