"""Change embeddings.message_id to String

Revision ID: ac76e8474eef
Revises: dd4318800d81
Create Date: 2025-03-26 19:33:22.977656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac76e8474eef'
down_revision: Union[str, None] = 'dd4318800d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embeddings', 'message_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('embeddings_message_id_fkey', 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'messages', ['message_id'], ['message_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key('embeddings_message_id_fkey', 'embeddings', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.alter_column('embeddings', 'message_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
