"""fix schema issues

Revision ID: dd4318800d81
Revises: 7fcdddb5ba0f
Create Date: 2025-03-25 19:03:33.654535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4318800d81'
down_revision: Union[str, None] = '7fcdddb5ba0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('classifications_message_id_fkey', 'classifications', type_='foreignkey')
    op.create_foreign_key(None, 'classifications', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('embeddings_message_id_fkey', 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'spaces', ['space_id'], ['room_id'], ondelete='CASCADE')
    op.drop_constraint('processed_messages_message_id_fkey', 'processed_messages', type_='foreignkey')
    op.create_foreign_key(None, 'processed_messages', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('thread_labels_solution_message_id_fkey', 'thread_labels', type_='foreignkey')
    op.create_foreign_key(None, 'thread_labels', 'messages', ['solution_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread_labels', type_='foreignkey')
    op.create_foreign_key('thread_labels_solution_message_id_fkey', 'thread_labels', 'messages', ['solution_message_id'], ['id'])
    op.drop_constraint(None, 'processed_messages', type_='foreignkey')
    op.create_foreign_key('processed_messages_message_id_fkey', 'processed_messages', 'messages', ['message_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key('embeddings_message_id_fkey', 'embeddings', 'messages', ['message_id'], ['id'])
    op.drop_constraint(None, 'classifications', type_='foreignkey')
    op.create_foreign_key('classifications_message_id_fkey', 'classifications', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###
